server:
  address:     ":8090"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

database:
  logger:
    path:    "temp/logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]

  default:
    link:   "mysql:root:root@tcp(127.0.0.1:3306)/test"
    debug:  true

redis:
  default:
    address: 127.0.0.1:6379
    db:      1

logger:
  level : "all"
  stdout: true

upload:
  path: "temp/upload"

qiniu:
  ak: "xxxx"
  sk: "xxxx"

