server:
  address:     ":8080"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

database:
  logger:
    path:    "temp/logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]

  default:
    link:   "mysql:root:root@tcp(192.168.1.224:3306)/test"
    debug:  true

logger:
  level : "all"
  stdout: true



