POST http://localhost:8090/backend/admin
Content-Type: application/json

{
  "name": "mrc",
  "password": "123456",
  "roleIds": "1",
  "isAdmin": 0
}

### get by id
GET http://localhost:8090/backend/admin/info/13