### Rotation
POST http://localhost:8080/backend/rotation
Content-Type: application/json

{
    "pic_url": "https://baidu.com",
    "link": "https://baidu.com",
    "sort": 1
}

### Rotation Delete
DELETE http://localhost:8080/backend/rotation/8

### Rotation Delete
PUT http://localhost:8080/backend/rotation/1
Content-Type: application/json

{
  "pic_url": "https://www.google.com",
  "link": "https://www.google.com",
  "sort": 2
}