// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-shop/internal/dao/internal"
)

// internalRotationDao is internal type for wrapping internal DAO implements.
type internalRotationDao = *internal.RotationDao

// rotationDao is the data access object for table rotation.
// You can define custom methods on it to extend its functionality as you wish.
type rotationDao struct {
	internalRotationDao
}

var (
	// Rotation is globally public accessible object for table rotation operations.
	Rotation = rotationDao{
		internal.NewRotationDao(),
	}
)

// Fill with you ideas below.
